export { default as ALayout } from './ALayout';
export { default as Dashboard } from './Dashboard';
export { default as Page } from './Page';
export { default as Media } from "./Media";
export { default as Project } from './Project';
export { default as Analytic } from './Analytic';
export { default as Profile } from './Profile';
export { default as Inbox } from './Inbox';
export { default as Setting } from './Setting';
export { default as Error } from '../../../utils/Error'